### PR TITLE
fix redis trace plugin

### LINKED ISSUE #503: sofa-tracer redis plugin未串联父span
### Actual behavior
拦截器中未在构建span前调用clientSend方法开启span并关联父span

导致执行完命令后，从context中取到的span为null

### Environment

- SOFATracer version: 3.1.2
- Redis plugin version：3.1.3-snapshot
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by Just-CJ**
### Motivation:

修复redis-plugin目前无法正常打印日志的问题

### Modification:

参考datasource-plugin中RedisSofaTracer中增加了startTrace和endTrace方法，并在RedisActionWrapperHelper中进行调用

### Result:

Fixes #503. 

## Summary by CodeRabbit

- **New Features**
	- Enhanced tracing capabilities with new methods for starting and ending traces.
	- Added constants for defining specific tags in tracing operations.
- **Improvements**
	- Simplified span management in tracing operations, reducing complexity.
	- Improved error handling and logging during tracing operations.

### CODE REVIEW

File: sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/tracer/RedisSofaTracer.java [hunk 1]
```diff
@@ -100,4 +113,41 @@ protected AbstractSofaTracerStatisticReporter getRedisClientStatReporter(String
...
 
     }
+
+    public SofaTracerSpan startTrace(String operationName) {
+        SofaTracerSpan sofaTracerSpan = clientSend(operationName);
+        if (this.appName == null) {
+            this.appName = SofaTracerConfiguration
+                .getProperty(SofaTracerConfiguration.TRACER_APPNAME_KEY);
+        }
+        SofaTracerSpanContext ctx = sofaTracerSpan.getSofaTracerSpanContext();
```
Comment (08fly) [inline sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/tracer/RedisSofaTracer.java]: modify variable name to express the role of variables

Comment (Just-CJ) [reply sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/tracer/RedisSofaTracer.java]: resolved

**Review by 08fly — APPROVED** [review]
LGTM
